# Generated by Django 2.2.4 on 2019-09-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='authors',
        ),
    ]
