# Generated by Django 2.2.4 on 2019-09-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20190912_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
