# Generated by Django 2.2.4 on 2019-09-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
