# Generated by Django 2.2.4 on 2019-09-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_orderproduct_product'),
        ('art', '0005_auto_20190913_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_produckt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.OrderProduct'),
            preserve_default=False,
        ),
    ]
