# Generated by Django 2.2.4 on 2019-09-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190913_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
