# Generated by Django 2.2.4 on 2019-09-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_address_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
    ]
