# Generated by Django 2.2.4 on 2019-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='orders',
            field=models.ManyToManyField(to='shop.Order'),
        ),
    ]
