# Generated by Django 2.2.4 on 2019-09-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_address_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='orders',
        ),
        migrations.AddField(
            model_name='address',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
            preserve_default=False,
        ),
    ]
