# Generated by Django 2.2.4 on 2019-09-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190917_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='orders',
        ),
    ]
