# Generated by Django 2.2.4 on 2019-09-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_address_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
