# Generated by Django 2.2.4 on 2019-09-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_address_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Client'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ManyToManyField(to='shop.OrderProduct'),
        ),
    ]
