# Generated by Django 2.2.4 on 2019-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_orderproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ManyToManyField(to='shop.Order'),
        ),
    ]
