# Generated by Django 2.2.4 on 2019-09-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190917_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ManyToManyField(to='shop.OrderProduct'),
        ),
    ]
