# Generated by Django 2.2.4 on 2019-09-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_remove_product_order_produckt'),
        ('shop', '0017_auto_20190917_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.Product'),
        ),
    ]
