# Generated by Django 2.2.4 on 2019-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
